services:
  postgres:
    image: postgres:16-alpine
    container_name: monkey_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: testapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: monkey_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/testapp
      FRONTEND_URL: https://test.monkeysdynasty.website
      BACKEND_URL: https://test.monkeysdynasty.website
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8001:8000"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ""
    container_name: monkey_frontend
    ports:
      - "127.0.0.1:5173:80"

volumes:
  postgres_data:
